eureka:
  client:
    serviceUrl:
      defaultZone: http://ec2-13-58-184-193.us-east-2.compute.amazonaws.com,http://ec2-13-58-128-97.us-east-2.compute.amazonaws.com,http://ec2-13-58-108-46.us-east-2.compute.amazonaws.com
      #http://eureka-primary:8011/eureka/,http://eureka-secondary:8012/eureka/,http://eureka-tertiary:8013/eureka/

---
spring:
  profiles: subject
words: I,You,He,She,It

---
spring:
  profiles: verb
words: ran,knew,had,saw,bought

---
spring:
  profiles: article
words: a,the

---
spring:
  profiles: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: noun
words: boat,book,vote,seat,backpack,partition,groundhog  
      
lucky-word: "Hello Anish"
